import "./globals.css";
import Layout from "@/commons/layout/02-02-layout-header-global";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* 02-02-layout-header-global */}
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
