import "./globals.css";
import Layout from "@/commons/layout/02-02-layout-header-global";
import LayoutGlobalAndLocal from "@/commons/layout/02-03-layout-header-local";
import LayoutGlobalAndLocalTransparent from "@/commons/layout/02-04-layout-header-local-transparent";
import LayoutShortAndLong from "@/commons/layout/02-05-layout-footer-short-and-long";
import DeviceSetting from "@/commons/settings/03-06-device-setting";
import DeviceSettingVariables from "@/commons/settings/05-01-device-setting-variables";
import DeviceSettingRedirect from "@/commons/settings/05-02-device-setting-redirect";
import DeviceSettingBack from "@/commons/settings/08-01-device-setting-back";
import DeviceSettingBackAndExit from "@/commons/settings/08-04-device-setting-back-and-exit";
import DeviceSettingViewTransition from "@/commons/settings/09-01-device-setting-view-transition";
import RoutingSettingViewTransition from "@/commons/settings/09-01-routing-setting-view-transition";
import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DeviceSettingViewTransition>
          <RoutingSettingViewTransition>
            {children}
          </RoutingSettingViewTransition>
        </DeviceSettingViewTransition>
      </body>
    </html>
  );
}
